### ISSUE TITLE
Please censor collection log popups so we don't have to go into settings each time we cox

### ISSUE THREAD

**Issue by mrwhisker23** [Karambtwo/cox-special-loot-hider#6]
There was an update so that the collection log popup occurs before you open the chest so there's no way to censor it with that enabled.

**Comment by b-licorice** [comment]
just wanted to bump this one for support since we just had our tbow spoiled this way :(

**Comment by Karambtwo** [comment]
Fixed in newest update, will be public when merged into RuneLite

**Comment by mrwhisker23** [comment]
Thanks, I appreciate the fix!
