### ISSUE TITLE
Does not censor the in-game loot drop notification

### ISSUE THREAD

**Issue by b-licorice** [Karambtwo/cox-special-loot-hider#7]
The in-game (i.e. client, not RuneLite) loot drop notification doesn't seem to be censored by this plugin currently. This is the one that is toggled in the game settings as "Loot drop notifications", and appears in the chat as "Valuable Drop: Rare Item (123,456,789 coins)".

As someone else also mentioned, the collection log popup censoring seems to be broken again.

**Comment by Karambtwo** [comment]
Just pushed a change that should censor the valuable drop message. Collection log broadcast censoring is still in the works

**Comment by Karambtwo** [comment]
Closing since another thread with pop up issue
